CREATE SEQUENCE IF NOT EXISTS SEQ_CODIGO_PRODUTO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_ENTRADA_ESTOQUE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_SAIDA_ESTOQUE START WITH 1 INCREMENT BY 1;