package io.github.mateuussilvapb.app_jm_perfumaria.application.produtoEntradaEstoque.mapper;

import io.github.mateuussilvapb.app_jm_perfumaria.application.common.movimentacaoEstoque.dto.ProdutoMovimentacaoEstoqueToViewUpdateResponseDto;
import io.github.mateuussilvapb.app_jm_perfumaria.domain.produtoEntradaEstoque.ProdutoEntradaEstoque;

public interface IProdutoEntradaEstoqueToProdutoEntradaEstoqueViewUpdateResponseDto {
    ProdutoMovimentacaoEstoqueToViewUpdateResponseDto toDto(ProdutoEntradaEstoque produtoEntradaEstoque);
}
