package io.github.mateuussilvapb.app_jm_perfumaria.application.produtoEntradaEstoque.mapper;

import io.github.mateuussilvapb.app_jm_perfumaria.application.common.movimentacaoEstoque.dto.ProdutoMovimentacaoEstoqueResponseListDto;
import io.github.mateuussilvapb.app_jm_perfumaria.domain.produtoEntradaEstoque.ProdutoEntradaEstoque;

public interface IProdutoEntradaEstoqueToProdutoEntradaEstoqueResponseListDto {
    ProdutoMovimentacaoEstoqueResponseListDto toDto(ProdutoEntradaEstoque produtoEntradaEstoque);
}
