package io.github.mateuussilvapb.app_jm_perfumaria.application.produtoSaidaEstoque.mapper;

import io.github.mateuussilvapb.app_jm_perfumaria.application.produtoSaidaEstoque.dto.ProdutoSaidaEstoqueResponseListDto;
import io.github.mateuussilvapb.app_jm_perfumaria.domain.produtoSaidaEstoque.ProdutoSaidaEstoque;

public interface IProdutoSaidaEstoqueToProdutoSaidaEstoqueResponseListDto {
    ProdutoSaidaEstoqueResponseListDto toDto(ProdutoSaidaEstoque produtoSaidaEstoque);
}
