package io.github.mateuussilvapb.app_jm_perfumaria.application.produtoSaidaEstoque.mapper;

import io.github.mateuussilvapb.app_jm_perfumaria.application.common.movimentacaoEstoque.dto.ProdutoMovimentacaoEstoqueToViewUpdateResponseDto;
import io.github.mateuussilvapb.app_jm_perfumaria.domain.produtoSaidaEstoque.ProdutoSaidaEstoque;

public interface IProdutoSaidaEstoqueToProdutoSaidaEstoqueViewUpdateResponseDto {
    ProdutoMovimentacaoEstoqueToViewUpdateResponseDto toDto(ProdutoSaidaEstoque produtoSaidaEstoque);
}
