package io.github.mateuussilvapb.app_jm_perfumaria.application.produtoSaidaEstoque.mapper;

import io.github.mateuussilvapb.app_jm_perfumaria.application.produtoSaidaEstoque.dto.ProdutoSaidaEstoqueToViewUpdateResponseDto;
import io.github.mateuussilvapb.app_jm_perfumaria.domain.produtoSaidaEstoque.ProdutoSaidaEstoque;

public interface IProdutoSaidaEstoqueToProdutoSaidaEstoqueViewUpdateResponseDto {
    ProdutoSaidaEstoqueToViewUpdateResponseDto toDto(ProdutoSaidaEstoque produtoSaidaEstoque);
}
